
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module DE1_SOC_D8M_LB_RTL(

	//////////// CLOCK //////////
	input 		          		CLOCK2_50,
	input 		          		CLOCK3_50,
	input 		          		CLOCK4_50,
	input 		          		CLOCK_50,

	//////////// SEG7 //////////
	output		     [6:0]		HEX0,
	output		     [6:0]		HEX1,
	output		     [6:0]		HEX2,
	output		     [6:0]		HEX3,
	output		     [6:0]		HEX4,
	output		     [6:0]		HEX5,

	//////////// KEY //////////
	input 		     [3:0]		KEY,

	//////////// LED //////////
	output		     [9:0]		LEDR,

	//////////// SW //////////
	input 		     [9:0]		SW,

	//////////// VGA //////////
	output		          		VGA_BLANK_N,
	output		     [7:0]		VGA_B,
	output		          		VGA_CLK,
	output		     [7:0]		VGA_G,
	output	reg	          		VGA_HS,
	output		     [7:0]		VGA_R,
	output		          		VGA_SYNC_N,
	output	reg	          		VGA_VS,

	//////////// GPIO_1, GPIO_1 connect to D8M-GPIO //////////
	inout 		          		CAMERA_I2C_SCL,
	inout 		          		CAMERA_I2C_SDA,
	output		          		CAMERA_PWDN_n,
	output		          		MIPI_CS_n,
	inout 		          		MIPI_I2C_SCL,
	inout 		          		MIPI_I2C_SDA,
	output		          		MIPI_MCLK,
	input 		          		MIPI_PIXEL_CLK,
	input 		     [9:0]		MIPI_PIXEL_D,
	input 		          		MIPI_PIXEL_HS,
	input 		          		MIPI_PIXEL_VS,
	output		          		MIPI_REFCLK,
	output		          		MIPI_RESET_n
);

//=============================================================================
// REG/WIRE declarations
//=============================================================================
  wire        AUTO_FOC ;
  wire        READ_Request ;
  wire 	[7:0]VGA_B_A;
  wire 	[7:0]VGA_G_A;
  wire 	[7:0]VGA_R_A;
  wire  [7:0]VGA_R_unfilt;
  wire  [7:0]VGA_G_unfilt;
  wire  [7:0]VGA_B_unfilt;
  wire  [7:0]VGA_R_filt;
  wire  [7:0]VGA_G_filt;
  wire  [7:0]VGA_B_filt;
  reg   [9:0]cursor1_x, cursor1_y;
  reg   [9:0]cursor2_x, cursor2_y;
  reg  [20:0]move_counter;
  wire        VGA_CLK_25M ;
  wire        RESET_N  ; 
  wire  [7:0]sCCD_R;
  wire  [7:0]sCCD_G;
  wire  [7:0]sCCD_B; 
  wire [15:0] H_Cont ; 
  wire [15:0] V_Cont ; 
  wire        I2C_RELEASE ;  
  wire        CAMERA_I2C_SCL_MIPI ; 
  wire        CAMERA_I2C_SCL_AF ;
  wire        CAMERA_MIPI_RELAESE ;
  wire        MIPI_BRIDGE_RELEASE ;
  wire        D8M_CK_HZ  ; 
  wire        D8M_CK_HZ2 ; 
  wire        D8M_CK_HZ3 ; 
  wire        RESET_KEY ; 
  wire   [9:0]MIPI_PIXEL_D_ ;
  wire        MIPI_PIXEL_VS_; 
  wire        MIPI_PIXEL_HS_;  
  
wire        LUT_MIPI_PIXEL_HS;
wire        LUT_MIPI_PIXEL_VS;
wire [9:0]  LUT_MIPI_PIXEL_D  ;
wire        MIPI_PIXEL_CLK_; 
//=======================================================
// Structural coding
//=======================================================

assign  MIPI_PIXEL_CLK_ = MIPI_PIXEL_CLK;


assign LUT_MIPI_PIXEL_HS=MIPI_PIXEL_HS;
assign LUT_MIPI_PIXEL_VS=MIPI_PIXEL_VS;
assign LUT_MIPI_PIXEL_D =MIPI_PIXEL_D ;


assign UART_RTS =0; 
assign UART_TXD =0; 
assign RESET_KEY      = ~SW[0];

//----- RESET RELAY  --		
RESET_DELAY			u2	(	
							.iRST  ( RESET_KEY ),
                     .iCLK  ( CLOCK2_50 ),				
						   .oREADY( RESET_N)  
							
						);

assign MIPI_RESET_n   = RESET_N;
assign CAMERA_PWDN_n  = RESET_KEY; 
assign MIPI_CS_n      = 0; 

//------ CAMERA I2C COM BUS --------------------
assign I2C_RELEASE    = CAMERA_MIPI_RELAESE & MIPI_BRIDGE_RELEASE; 
assign CAMERA_I2C_SCL = ( I2C_RELEASE  )? CAMERA_I2C_SCL_AF  : CAMERA_I2C_SCL_MIPI ;   
 
//------ MIPI BRIDGE  I2C SETTING--------------- 
MIPI_BRIDGE_CAMERA_Config    cfin(
   .RESET_N           ( RESET_N  ), 
   .CLK_50            ( CLOCK2_50), 
   .MIPI_I2C_SCL      ( MIPI_I2C_SCL ), 
   .MIPI_I2C_SDA      ( MIPI_I2C_SDA ), 
   .MIPI_I2C_RELEASE  ( MIPI_BRIDGE_RELEASE ),  
   .CAMERA_I2C_SCL    ( CAMERA_I2C_SCL_MIPI ),
   .CAMERA_I2C_SDA    ( CAMERA_I2C_SDA ),
   .CAMERA_I2C_RELAESE( CAMERA_MIPI_RELAESE )
);
 
//-- Video PLL --- 

pll_test ref(
		.refclk   ( CLOCK_50  ),   
		.rst      ( 1'b0 ),     
		.outclk_0 ( MIPI_REFCLK )//20m
		//20M

	);


vga_pll pllv(
		.refclk   (CLOCK4_50),   
		.rst      ( 1'b0 ),     
		.outclk_0( VGA_CLK_25M ) //25M
  
	);

//--- D8M RAWDATA to RGB ---
D8M_SET   ccd (
	.RESET_SYS_N  ( RESET_N ),
   .CLOCK_50     ( CLOCK2_50      ),
	.CCD_DATA     ( LUT_MIPI_PIXEL_D [9:0]) ,
	.CCD_FVAL     ( LUT_MIPI_PIXEL_VS ), //60HZ
	.CCD_LVAL	  ( LUT_MIPI_PIXEL_HS ), // 
	.CCD_PIXCLK   ( MIPI_PIXEL_CLK_), //25MHZ
	.READ_EN      (READ_Request) ,
   .VGA_HS       ( VGA_HS ),
   .VGA_VS       ( VGA_VS ),	
	.X_Cont       ( H_Cont),  
   .Y_Cont       ( V_Cont),   
   .sCCD_R       ( sCCD_R ),
   .sCCD_G       ( sCCD_G ),
   .sCCD_B       ( sCCD_B )
);


//--- VGA interface signals ---
assign VGA_CLK    = MIPI_PIXEL_CLK_;
assign VGA_SYNC_N = 1'b0;

// READ_Request: active during valid pixel region
assign READ_Request = ((H_Cont > 16'd160 && H_Cont < 16'd800) &&
                       (V_Cont > 16'd045 && V_Cont < 16'd525));

// Blanking signal (active low)
assign VGA_BLANK_N = ~((H_Cont < 16'd160) || (V_Cont < 16'd045));

// Pixel data gated by blanking
assign VGA_R_A = VGA_BLANK_N ? sCCD_R : 8'h00;
assign VGA_G_A = VGA_BLANK_N ? sCCD_G : 8'h00;
assign VGA_B_A = VGA_BLANK_N ? sCCD_B : 8'h00;

// Generate horizontal and vertical sync signals
always @(*) begin
   if ((H_Cont >= 16'd002) && (H_Cont <= 16'd097))
      VGA_HS = 1'b0;
   else
      VGA_HS = 1'b1;

   if ((V_Cont >= 16'd013) && (V_Cont <= 16'd014))
      VGA_VS = 1'b0;
   else
      VGA_VS = 1'b1;
end

//------AOTO FOCUS ENABLE  --
AUTO_FOCUS_ON  adj( 
                      .CLK_50      ( CLOCK2_50 ), 
                      .I2C_RELEASE ( I2C_RELEASE ), 
                      .AUTO_FOC    ( AUTO_FOC )
               ) ;
//------Auto focus ------- 
FOCUS_ADJ adl(
     .CLK_50        ( CLOCK2_50   ), 
     .RESET_N       ( I2C_RELEASE ), 
     .RESET_SUB_N   ( I2C_RELEASE ), 
     .AUTO_FOC      ( KEY[3] & AUTO_FOC ),   
     .SW_FUC_LINE   ( SW[3] ),
     .SW_FUC_ALL_CEN( SW[3] ),
     .VIDEO_HS      ( VGA_HS),
     .VIDEO_VS      ( VGA_VS),
     .VIDEO_CLK     ( VGA_CLK),
     .VIDEO_DE      (READ_Request) ,
     .iR            ( VGA_R_A), 
     .iG            ( VGA_G_A), 
     .iB            ( VGA_B_A), 
     
     .oR            ( VGA_R_unfilt),
     .oG            ( VGA_G_unfilt),
     .oB            ( VGA_B_unfilt),
     
     .READY         (  READY),
     .SCL           ( CAMERA_I2C_SCL_AF ), 
     .SDA           ( CAMERA_I2C_SDA    )
);

//--- RGB color filters ---
// SW[2:1]: Red   - 00=normal, 01=half, 10=quarter, 11=off
// SW[4:3]: Green - 00=normal, 01=half, 10=quarter, 11=off
// SW[6:5]: Blue  - 00=normal, 01=half, 10=quarter, 11=off
assign VGA_R_filt = (SW[2:1] == 2'b00) ? VGA_R_unfilt :
                    (SW[2:1] == 2'b01) ? {1'b0, VGA_R_unfilt[7:1]} :
                    (SW[2:1] == 2'b10) ? {2'b00, VGA_R_unfilt[7:2]} :
                    8'h00;

assign VGA_G_filt = (SW[4:3] == 2'b00) ? VGA_G_unfilt :
                    (SW[4:3] == 2'b01) ? {1'b0, VGA_G_unfilt[7:1]} :
                    (SW[4:3] == 2'b10) ? {2'b00, VGA_G_unfilt[7:2]} :
                    8'h00;

assign VGA_B_filt = (SW[6:5] == 2'b00) ? VGA_B_unfilt :
                    (SW[6:5] == 2'b01) ? {1'b0, VGA_B_unfilt[7:1]} :
                    (SW[6:5] == 2'b10) ? {2'b00, VGA_B_unfilt[7:2]} :
                    8'h00;

//--- Grayscale conversion ---
// SW[7]: grayscale enable - down=color, up=grayscale
// Luminance = 0.2126*R + 0.7152*G + 0.0722*B
// Coefficients in 8-bit fractional: 54/256, 183/256, 19/256
wire [15:0] lum_r = VGA_R_unfilt * 8'd54;
wire [15:0] lum_g = VGA_G_unfilt * 8'd183;
wire [15:0] lum_b = VGA_B_unfilt * 8'd19;
wire [15:0] lum_sum = lum_r + lum_g + lum_b;
wire  [7:0] luminance = lum_sum[15:8];

//--- Cursor system ---
// SW[9]: cursor select - down=3x3 block, up=10x10 box
// KEY[0]: left, KEY[1]: right, KEY[2]: down, KEY[3]: up

// Screen pixel coordinates (0-based in active region)
wire [15:0] pixel_x = H_Cont - 16'd160;
wire [15:0] pixel_y = V_Cont - 16'd045;

// Cursor 1: 3x3 solid block
wire [15:0] c1x = {6'd0, cursor1_x};
wire [15:0] c1y = {6'd0, cursor1_y};
wire cursor1_here = (pixel_x >= c1x) && (pixel_x < c1x + 16'd3) &&
                    (pixel_y >= c1y) && (pixel_y < c1y + 16'd3);

// Cursor 2: 10x10 box with 1-pixel border (hollow)
wire [15:0] c2x = {6'd0, cursor2_x};
wire [15:0] c2y = {6'd0, cursor2_y};
wire cursor2_here = (pixel_x >= c2x) && (pixel_x < c2x + 16'd10) &&
                    (pixel_y >= c2y) && (pixel_y < c2y + 16'd10) &&
                    (pixel_x == c2x || pixel_x == c2x + 16'd9 ||
                     pixel_y == c2y || pixel_y == c2y + 16'd9);

wire cursor_active = VGA_BLANK_N && (cursor1_here || cursor2_here);

// Cursor movement (clocked at ~24 Hz from 50 MHz)
always @(posedge CLOCK_50 or negedge RESET_N) begin
   if (!RESET_N) begin
      cursor1_x    <= 10'd316;
      cursor1_y    <= 10'd236;
      cursor2_x    <= 10'd310;
      cursor2_y    <= 10'd230;
      move_counter <= 21'd0;
   end else begin
      move_counter <= move_counter + 1;
      if (move_counter == 21'd0) begin
         if (!SW[9]) begin
            if (!KEY[0] && cursor1_x > 0)   cursor1_x <= cursor1_x - 1;
            if (!KEY[1] && cursor1_x < 637) cursor1_x <= cursor1_x + 1;
            if (!KEY[3] && cursor1_y > 0)   cursor1_y <= cursor1_y - 1;
            if (!KEY[2] && cursor1_y < 477) cursor1_y <= cursor1_y + 1;
         end else begin
            if (!KEY[0] && cursor2_x > 0)   cursor2_x <= cursor2_x - 1;
            if (!KEY[1] && cursor2_x < 630) cursor2_x <= cursor2_x + 1;
            if (!KEY[3] && cursor2_y > 0)   cursor2_y <= cursor2_y - 1;
            if (!KEY[2] && cursor2_y < 470) cursor2_y <= cursor2_y + 1;
         end
      end
   end
end

// Final VGA output: cursor > grayscale > color filter
assign VGA_R = cursor_active ? 8'h00 : (SW[7] ? luminance : VGA_R_filt);
assign VGA_G = cursor_active ? 8'hFF : (SW[7] ? luminance : VGA_G_filt);
assign VGA_B = cursor_active ? 8'hFF : (SW[7] ? luminance : VGA_B_filt);


//--Frame Counter -- 
 FpsMonitor uFps2(
	  .clk50    ( CLOCK2_50 ),
	  .vs       ( VGA_VS    ),//LUT_MIPI_PIXEL_VS ), //60HZ
	  .fps      (  ),
	  .hex_fps_h( HEX1 ),
	  .hex_fps_l( HEX0 )
);


//----7-SEG OFF----
assign  HEX2 = 7'h7F;
assign  HEX3 = 7'h7F;
assign  HEX4 = 7'h7F;
assign  HEX5 = 7'h7F;


//--FREQUNCY TEST--
CLOCKMEM  ck1 ( .CLK(VGA_CLK_25M    ),.CLK_FREQ  (25000000  ),.CK_1HZ (D8M_CK_HZ   ));
CLOCKMEM  ck2 ( .CLK(MIPI_REFCLK    ),.CLK_FREQ  (20000000  ),.CK_1HZ (D8M_CK_HZ2  ));
CLOCKMEM  ck3 ( .CLK(MIPI_PIXEL_CLK_),.CLK_FREQ  (25000000 ),.CK_1HZ (D8M_CK_HZ3   ));

//--LED STATUS-----
assign LEDR[9:0] = { D8M_CK_HZ ,D8M_CK_HZ2,D8M_CK_HZ3 ,5'h0,CAMERA_MIPI_RELAESE ,MIPI_BRIDGE_RELEASE } ; 
endmodule



